apiVersion: v1
kind: Pod
metadata:
  name: configmap-pod
spec:
  containers:
  - image: busybox
    name: configmap-pod
    command: ['sh', '-c', 'while true; do sleep 3600; done']
    env: 
    - name: ENV_CONFIG
      valueFrom:
        configMapKeyRef:
          name: my-configmap
          key: config.json
    envFrom:
      - configMapRef:
          name: app1-config
