apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  storageClassName: nfs-sc
  capacity:
    storage: 100Mi
  accessModes:
  - ReadWriteMany
  nfs:
    server: 192.168.1.100
    path: /var/nfs/data1

