apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  #  volumeName: test-pv
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi 
