apiVersion: v1
kind: Pod
metadata:
  name: custom-web
  labels:
    app: web
spec:
  initContainers:
  - name: prepare
    image: busybox
    command: ['sh', '-c', 'echo "<html><h1>Webpage from init container</h1></html>" > /work-dir/index.html' ]
    volumeMounts:
    - name: workdir
      mountPath: /work-dir
  containers:
  - name: c1
    image: nginx:1.14.2
    volumeMounts:
    - name: workdir
      mountPath: /usr/share/nginx/html
  volumes:
  - name: workdir
    emptyDir: {}
