apiVersion: v1
kind: Pod
metadata:
  name: init-pod
spec:
  containers:
    - name: nginx
      image: nginx
  initContainers:
    - name: delay
      image: busybox
      command: ['sh', '-c', 'sleep 30; echo init job is done']

