apiVersion: v1 
kind: Pod
metadata:
  name: my-pod 
  labels:
    app: test-pod
spec: # container specification
  containers:
  - name: busybox # container name
    image: 'radial/busyboxplus:curl'
    command: [ 'sh', '-c', 'while true; do sleep 3600; done']
